import random
from services import ConfigurationService, DataService
from itertools import zip_longest

class RecipeGeneratorService():
    configuration_service: ConfigurationService = None
    data_service: DataService = None

    def __init__(
            self,
            configuration_service: ConfigurationService,
            data_service: DataService):
        self.configuration_service = configuration_service
        self.data_service = data_service

    def create_recipe(self):
        '''
        Returns a recipe represented as a list of pairs of numbers, the first value of
        a pair being an FDC food ID and the second number being a portion size in percent
        of 100 grams.
        '''

        food_ids = self.data_service.unique_fdc_ids
        food_ids_length = len(food_ids)
        reqd_base_ingredient_ids = self.configuration_service.required_base_foods

        ingredients = list(map(
            lambda _: food_ids[random.choice(range(food_ids_length))],
            # One less because one slot is required for the base ingredient
            range(self.configuration_service.recipe_size - 1))
        ) + [
            # Reserved slot for required base ingredient
            reqd_base_ingredient_ids[random.choice(range(len(reqd_base_ingredient_ids)))]
        ]

        portions = list(map(
            lambda _: random.choice(range(1, 283)) / 100,
            range(self.configuration_service.recipe_size))
        )

        return list(zip_longest(ingredients, portions))

    def get_nutrient_report(self, recipe: list):
        '''
        Given a recipe in the format generated by create_recipe(), return a dictionary
        of pairs, the first value being a nutrient ID and the second value being the
        amount of the nutrient present in the recipe.
        '''
